service:
  name: lol-live-backend

plugins:
  - serverless-webpack
  - serverless-iam-roles-per-function

custom:
  serverless-iam-roles-per-function:
    defaultInherit: true

provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1
  stage: dev

functions:
  getSummonerByName:
    handler: services/getSummonerByName/handler.main
    iamRoleStatements:
      - Effect: Allow
        Action:
          - 'secretsmanager:GetResourcePolicy'
          - 'secretsmanager:GetSecretValue'
          - 'secretsmanager:DescribeSecret'
          - 'secretsmanager:ListSecretVersionIds'
        Resource: '*'
    events:
      - http:
          method: post
          path: getSummonerByName
          cors: true
  
  getMatchHistory:
    handler: services/getMatchHistory/handler.main
    iamRoleStatements:
      - Effect: Allow
        Action:
          - 'secretsmanager:GetResourcePolicy'
          - 'secretsmanager:GetSecretValue'
          - 'secretsmanager:DescribeSecret'
          - 'secretsmanager:ListSecretVersionIds'
        Resource: '*'
    events:
      - http:
          method: post
          path: getMatchHistory
          cors: true

  getActiveGame:
    handler: services/getActiveGame/handler.main
    iamRoleStatements:
      - Effect: Allow
        Action:
          - 'secretsmanager:GetResourcePolicy'
          - 'secretsmanager:GetSecretValue'
          - 'secretsmanager:DescribeSecret'
          - 'secretsmanager:ListSecretVersionIds'
        Resource: '*'
    events:
      - http:
          method: post
          path: getActiveGame
          cors: true

  getSummonerStats:
    handler: services/getSummonerStats/handler.main
    iamRoleStatements:
      - Effect: Allow
        Action:
          - 'secretsmanager:GetResourcePolicy'
          - 'secretsmanager:GetSecretValue'
          - 'secretsmanager:DescribeSecret'
          - 'secretsmanager:ListSecretVersionIds'
        Resource: '*'
    events:
      - http:
          method: post
          path: getSummonerStats
          cors: true
resources:
  - ${file(resources/api-gateway-errors.yml)}