service:
  name: lol-live-backend

plugins:
  - serverless-webpack
  - serverless-iam-roles-per-function

custom:
  serverless-iam-roles-per-function:
    defaultInherit: true

provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1
  stage: prod

functions:
  getSummonerByName:
    handler: services/getSummonerByName/handler.main
    iamRoleStatements:
      - Effect: Allow
        Action:
          - 'secretsmanager:GetResourcePolicy'
          - 'secretsmanager:GetSecretValue'
          - 'secretsmanager:DescribeSecret'
          - 'secretsmanager:ListSecretVersionIds'
        Resource: '*'
    events:
      - http:
          method: get
          path: getSummonerByName
          cors:       
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: true

resources:
  - ${file(resources/api-gateway-errors.yml)}